/**
 * Task page definitions.
 * Reads from taskPages.json (generated by preprocessing) to create
 * aggregation pages for homework, exams, projects.
 */

const fs = require('fs');
const path = require('path');

module.exports = function() {
  try {
    const dataPath = path.join(__dirname, 'taskPages.json');
    const pages = JSON.parse(fs.readFileSync(dataPath, 'utf-8'));
    return pages.map(page => ({
      type: page.type,
      title: page.title,
      slug: page.slug,
      taskType: page.type === 'exam' ? 'exams' : page.type === 'homework' ? 'homework' : 'projects',
    }));
  } catch (e) {
    // Default task pages if config not yet generated
    return [
      { type: 'homework', title: 'Tareas', slug: 'tareas', taskType: 'homework' },
      { type: 'exam', title: 'Examenes', slug: 'examenes', taskType: 'exams' },
      { type: 'project', title: 'Proyectos', slug: 'proyectos', taskType: 'projects' },
    ];
  }
};
