/**
 * Markdown pipeline configuration.
 * markdown-it + dollarmath + containers + attrs + anchors
 */

const fs = require('fs');
const nodePath = require('path');
const markdownIt = require('markdown-it');
const markdownItContainer = require('markdown-it-container');
const markdownItAttrs = require('markdown-it-attrs');
const markdownItAnchor = require('markdown-it-anchor');
const { renderComponent, COMPONENT_TYPES } = require('./components');

/**
 * Load wikilink resolution data (generated by Python preprocessing).
 * Called once at module init. Falls back to empty map if not yet generated.
 */
function loadWikilinkData() {
  const dataDir = nodePath.join(__dirname, '..', '_data');
  let map = {};
  let prefix = '';

  try {
    map = JSON.parse(fs.readFileSync(nodePath.join(dataDir, 'wikilink_map.json'), 'utf-8'));
  } catch { /* map not generated yet */ }

  // Path prefix: same source chain as path-prefix.js
  if (process.env.PATH_PREFIX !== undefined) {
    prefix = process.env.PATH_PREFIX;
  } else {
    try {
      const repo = JSON.parse(fs.readFileSync(nodePath.join(dataDir, 'repo.json'), 'utf-8'));
      prefix = repo.base_url || '';
    } catch { /* no prefix */ }
  }

  // Normalize: remove trailing slash (URLs in map start with /)
  prefix = prefix.replace(/\/$/, '');

  return { map, prefix };
}

function configureMarkdown() {
  const md = markdownIt({
    html: true,
    breaks: false,
    linkify: true,
    typographer: false, // IMPORTANT: false prevents -- -> en-dash (breaks LaTeX)
  });

  // Inline math plugin: protects $...$ and $$...$$ from markdown processing.
  // Renders as <span class="math-inline"> / <div class="math-display">
  // for client-side KaTeX rendering. No external dependency needed.
  md.inline.ruler.after('escape', 'math_inline', (state, silent) => {
    const src = state.src;
    const start = state.pos;

    if (src.charCodeAt(start) !== 0x24 /* $ */) return false;

    // $$...$$ display math (inline context)
    if (src.charCodeAt(start + 1) === 0x24) {
      const end = src.indexOf('$$', start + 2);
      if (end === -1) return false;
      if (!silent) {
        const token = state.push('math_display_inline', 'div', 0);
        token.content = src.slice(start + 2, end);
        token.markup = '$$';
      }
      state.pos = end + 2;
      return true;
    }

    // $...$ inline math — skip if next char is digit or space
    const next = src.charCodeAt(start + 1);
    if (next === 0x20 || next === 0x0A || (next >= 0x30 && next <= 0x39)) return false;

    const end = src.indexOf('$', start + 1);
    if (end === -1 || end === start + 1) return false;
    // No space before closing $
    if (src.charCodeAt(end - 1) === 0x20) return false;

    if (!silent) {
      const token = state.push('math_inline', 'span', 0);
      token.content = src.slice(start + 1, end);
      token.markup = '$';
    }
    state.pos = end + 1;
    return true;
  });

  // $$...$$ display math as block
  md.block.ruler.before('fence', 'math_display', (state, startLine, endLine, silent) => {
    const startPos = state.bMarks[startLine] + state.tShift[startLine];
    if (state.src.charCodeAt(startPos) !== 0x24 || state.src.charCodeAt(startPos + 1) !== 0x24) return false;

    // Find closing $$
    let nextLine = startLine + 1;
    while (nextLine < endLine) {
      const pos = state.bMarks[nextLine] + state.tShift[nextLine];
      const max = state.eMarks[nextLine];
      const line = state.src.slice(pos, max).trim();
      if (line === '$$') break;
      nextLine++;
    }
    if (nextLine >= endLine) return false;
    if (silent) return true;

    const token = state.push('math_display', 'div', 0);
    token.content = state.getLines(startLine + 1, nextLine, state.tShift[startLine], false).trim();
    token.markup = '$$';
    token.map = [startLine, nextLine + 1];
    state.line = nextLine + 1;
    return true;
  });

  md.renderer.rules.math_inline = (tokens, idx) =>
    `<span class="math-inline">${md.utils.escapeHtml(tokens[idx].content)}</span>`;
  md.renderer.rules.math_display = (tokens, idx) =>
    `<div class="math-display">${md.utils.escapeHtml(tokens[idx].content)}</div>`;
  md.renderer.rules.math_display_inline = (tokens, idx) =>
    `<div class="math-display">${md.utils.escapeHtml(tokens[idx].content)}</div>`;

  // Wikilinks: [[target]] and [[target|display text]]
  const wikilinkData = loadWikilinkData();

  md.inline.ruler.after('escape', 'wikilink', (state, silent) => {
    const src = state.src;
    const start = state.pos;

    if (src.charCodeAt(start) !== 0x5B || src.charCodeAt(start + 1) !== 0x5B) return false;

    const end = src.indexOf(']]', start + 2);
    if (end === -1) return false;

    if (!silent) {
      const inner = src.slice(start + 2, end);
      const pipeIdx = inner.indexOf('|');
      const target = (pipeIdx >= 0 ? inner.slice(0, pipeIdx) : inner).trim();
      const display = pipeIdx >= 0 ? inner.slice(pipeIdx + 1).trim() : null;

      const hashIdx = target.indexOf('#');
      const targetKey = (hashIdx >= 0 ? target.slice(0, hashIdx) : target).toLowerCase();
      const fragment = hashIdx >= 0 ? target.slice(hashIdx) : '';

      const resolved = wikilinkData.map[targetKey];

      if (resolved) {
        const token = state.push('wikilink_open', 'a', 1);
        token.attrSet('href', wikilinkData.prefix + resolved.url + fragment);
        token.attrSet('class', 'wikilink');
        const text = state.push('text', '', 0);
        text.content = display || resolved.title;
        state.push('wikilink_close', 'a', -1);
      } else {
        const token = state.push('html_inline', '', 0);
        token.content = '<span class="wikilink-broken" title="No resuelto: '
          + md.utils.escapeHtml(target) + '">'
          + md.utils.escapeHtml(display || target) + '</span>';
      }
    }

    state.pos = end + 2;
    return true;
  });

  // Attributes: {.class #id key=value}
  md.use(markdownItAttrs);

  // Anchors: add IDs to headings
  md.use(markdownItAnchor, {
    permalink: markdownItAnchor.permalink.headerLink(),
    slugify: s => s.toLowerCase().replace(/[^\w]+/g, '-'),
  });

  // Component containers: :::homework{...}, :::exercise{...}, etc.
  COMPONENT_TYPES.forEach(type => {
    md.use(markdownItContainer, type, {
      validate: params => params.trim().match(new RegExp(`^${type}\\s*(.*)$`)),
      render: (tokens, idx) => renderComponent(tokens, idx, type, md),
    });
  });

  return md;
}

module.exports = { configureMarkdown };
